name: main
type: php:7.4

hooks:
  build: |
    set -e

    export tag="$(cat latest-tag)"
    export filename=webpaas.phar

    [ -d cli ] && rm -rf cli
    git clone --branch "$tag" https://github.com/platformsh/platformsh-cli.git cli

    cp config.yaml cli/config.yaml
    cd cli/vendor-bin/box
    composer install --no-interaction
    cd -
    cd cli
    export version="$(git describe --tags)"
    composer install --no-dev --no-interaction
    mkdir -p vendor/bin
    ln -s "$(realpath vendor-bin/box/vendor/bin/box)" vendor/bin/box
    ./bin/platform self:build --no-composer-rebuild --replace-version="$version" --yes --output ../web/"$filename"
    cd -

    cat << EOF > .environment
    export CLI_URL_PATH=$filename
    export CLI_BUILD_DATE="$(date)"
    export CLI_VERSION="$version"
    EOF

    export sha256="$(sha256sum web/"$filename" | cut -f1 -d' ')"
    cat <<EOF > web/manifest.json
    [
      {
        "version": "$(echo -n "$version" | tail -c +2)",
        "sha256": "$sha256",
        "name": "$filename",
        "url": "$filename"
      }
    ]
    EOF
    cp cli/dist/installer.php web/installer

web:
  locations:
    '/':
      root: web
      index: ['index.php']
      expires: 15m

source:
  operations:
    update:
      command: |
        set -e
        git clone https://github.com/platformsh/platformsh-cli.git cli
        cd cli
        export latest="$(git describe --tags --abbrev=0)"
        echo "$latest" > ../latest-tag
        cd ..
        if ! git diff --quiet ; then
          git add latest-tag
          git commit -m "Automatic update to latest version"
        else
          echo 'Already at the latest version'
        fi
